### ISSUE TITLE
seamless-immutable

### ISSUE THREAD

**Issue by natew** [foss-haas/fynx#16]
Just read [this](http://noredinktech.tumblr.com/post/107617838018/switching-from-immutable-js-to-seamless-immutable) and saw [seamless-immutable](https://github.com/rtfeldman/seamless-immutable). No cursors yet, but would be cool to add support for other libraries down the road.

**Comment by pluma** [comment]
The project Fynx was born out of requires IE8 compatibility, so until IE8 is fully eradicated in the public service in Germany, I don't see Fynx moving to anything that requires ES5 yet. Sorry :disappointed:
