### ISSUE TITLE
Replace mixins with higher-order components for React 0.13

### ISSUE THREAD

**Issue by StevenLangbroek** [foss-haas/fynx#18]
Have you thought about React 0.13 compatibility re: the [deprecation of Mixins](medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750)? [Martyjs](http://martyjs.org/guides/containers/index.html) offers `Marty.createContainer` to work around this, would love to hear your thoughts.

**Comment by pluma** [comment]
Interesting. I only heard that mixins wouldn't be supported for the ES6 class syntax.

I'll sort out any pressing issues for 1.x and then work on a major release that'll use higher-order components instead of mixins.

**Comment by StevenLangbroek** [comment]
Awesome :) yeah I'm not a fan of ES6 class syntax (see [this gist](https://gist.github.com/StevenLangbroek/e938ceaa15469b086ab5)), but we'll have to make do.

**Comment by pluma** [comment]
If React wants ES6 classes, I'll use ES6 classes. Simple as that ;)

**Comment by StevenLangbroek** [comment]
Amen.

**Comment by StevenLangbroek** [comment]
It's been a while, and I was wondering if you had any thoughts on this? Another option, that Baobab exposes for example, is [using decorators](https://github.com/Yomguithereal/baobab-react#decorators). Would you like help with this?

**Comment by pluma** [comment]
I'm currently planning to start with the 2.0 rewrite next month as I will (hopefully) finally be working on the software using this library again. Right now I'm thinking about a better representation of the state and sorting out the routing and async resource loading. I'm a bit unhappy with how it's currently solved with stores and would like the "stores" to be passed in as props rather than globals.

**Comment by pluma** [comment]
I'll probably extract the mixins out of the core module as I plan to replace the current mixin-based data binding in our application with pure components (and contexts where necessary).

As this wouldn't be dogfooded anymore, I'm fine providing decorators or [higher order components](https://gist.github.com/sebmarkbage/ef0bf1f338a7182b6775#file-enhance-js) or both.

**Comment by pluma** [comment]
I've experimentally implemented the connect and connectProps decorators at https://github.com/foss-haas/fynx-decorators

The mixins have been moved out of Fynx 2 and now live at https://github.com/foss-haas/fynx-mixins

I can't think of any clever ways to implement connectVia, listenTo or listenToProp as decorators, so I've removed them from the decorators repo for now.

Any further discussion of decorators and mixins should probably take place at the dedicated repos.
