### ISSUE TITLE
Pass keyPath to listen

### ISSUE THREAD

**Issue by natew** [foss-haas/fynx#19]
Currently just the new data is passed through, but Immutable also passes the oldData and keyPath as second and third args for `Cursor.from`, would be nice to pass those through as well to `.listen`.

I'd like to do a listen and the store and sync to localStorage, but don't want to degrade performance too much so a keypath would help.

**Comment by pluma** [comment]
Is this still needed? I don't see any way of implementing this without breaking backwards compatibility.

`axn` currently only supports emitting a single value, so it would have to be wrapped in an array, which would probably be bad.
