### ISSUE TITLE
Insert object automatically become immutable

### ISSUE THREAD

**Issue by natew** [foss-haas/fynx#6]
I think this is more of a immutable question, but wondering, since this library seems to be strictly immutable in it's usage.  I ran into a weird case here. Let's say I'm updating a store:

```js
Actions.loadArticle.listen(
  id => API.get(`item/${id}.json`)
    .then(
      res => ArticlesStore().update(id, article => res),
      error
    ));
```

This works, but when I later listen on the store and run a ArticlesStore().get(id), the data is returned as a regular JS object rather than an immutable one.

Now, maybe I'm just allergic to importing unnecessarily because I know I could just change the line to be `update(id, article => Immutable.fromJS(res))`, but it seems a bit verbose to have to import immutable just to do that when we probably always want our store to contain immutable data.

Wondering, does immutable provide or fynx provide a way to hook into these actions to have a converter step there that can take care of that for me?

**Comment by natew** [comment]
@pluma any word on this, I just checked and it looks like 3.6 was released.

**Comment by pluma** [comment]
Thanks for pointing that out. I'll try and add functionality that'll use this in the next release.

**Comment by natew** [comment]
Not sure where to put this, but I did a little write up on Fynx: http://localhost:4000/2015/03/11/Simplify-Flux-with-Immutable-js-and-Fynx/

Tried to get it onto the HN homepage but no luck this time :wink:

**Comment by pluma** [comment]
Wow. Awesome, thanks.

The project we originally developed Fynx for went live earlier this month, so hopefully I'll find some time in the coming weeks to clean it up a bit and address the issues that have come up in the meantime. We'll be maintaining the project (and Fynx) for the foreseeable future and keep using Fynx for other projects, so please don't misinterpret the radio silence of the past months. I've simply been ridiculously busy ;)

**Comment by natew** [comment]
In the same boat as you. So many packages I need to show some love. I understand. Can I ask what you built?

**Comment by natew** [comment]
Trying to make some changes in a fork but even with dist-watch and it linked in, I can't seem to get it to see my changes. May need more time, but would be awesome to have createCursorStore also cast to immutable along with updates.

**Comment by natew** [comment]
Tried again on this but for some reason using npm link I can't get webpack to pick up my changes, building to /lib and all. Not sure why :unamused:
