### ISSUE TITLE
Pattern for listening to actions finishing

### ISSUE THREAD

**Issue by natew** [foss-haas/fynx#7]
So far I've been doing something like this:

```js
Fynx.createActions('refresh', 'refreshDone');
Actions.refresh.listen(() => doPromisedStuff().then(refreshDone));
```

And in my views:

```js
Actions.refresh()
var unlisten = Actions.refreshDone.listen(() => {
  // do something
  unlisten();
});
```

It's not painful at all, but I keep wanting to have promises at my fingertips for actions, so I could do something like this instead in my views:

```js
Actions.refresh().then(() => {
  // do something...
});
```

Just wondering your thoughts on both the first pattern (is it the "right way"?) and also the feasibility of allowing promises to return from actions? I'd be willing to prototype, but I haven't looked into the source much so I'm not sure if there are technical reasons not to do it.

**Comment by pluma** [comment]
I've implemented return values and async actions (via promises) in [axn 1.5.0](https://www.npmjs.com/package/axn). Does this solve the issue for you?

**Comment by pluma** [comment]
Async actions are now supported as of 1.6, see 944640e3998bfaf078b0985d8182c2c56d95f820. I've adjusted the example to use async actions. I hope this solves the problems you had.

If this isn't enough, feel free to hit me up on gitter or respond here and I'll reopn the issue if necessary.

**Comment by natew** [comment]
Just want to say thanks for this. I'm using them in my app now and have reduced a huge amount of code!

I know we spoke about this, but just wondering, this still would break if unmount happens before the action is finished right?

```js
Actions.articlesHotLoad({ nocache: true }).then(() => {
  this.setState({ isRefreshing: false });
});
```

As in, if the component unmounts but the action finishes, it would have an error? I wonder if there wouldn't be a way to make a mixin that helps you with that automatically, i.e. if a component unmounts it unlistens to the promise. Or does some other fancy thing. Not sure exactly, but just wondering your thoughts on that.

**Comment by pluma** [comment]
The promises returned by async actions are cancellable. So you can do this:

```js
getInitialState() { // or wherever
  this.promises = [];
  return {};
},
doSomething() {
  var p = Actions.doStuff({foo: 'bar'});
  this.promises.push(p);
  p.then(
    (data) => this.yay(data),
    (err) => {
      if (p.cancelled()) return;
      this.recoverFromError(err);
    }
  ).then(() => this.promises.splice(this.promises.indexOf(p), 1));
},
componentWillUnmount() {
  this.promises.forEach(p => p.cancel());
}
```

In other words: you cancel them on unmount so all promises will fail (note that this does not interrupt whatever else the action is doing at that moment, it just prevents further listeners from being triggered and rejects the promise with an error). Then you can check whether the promise failed because it was cancelled in your error recovery.

I'm using properties directly in the example to avoid messing with the state. You could run into problems otherwise if you try to `setState` after unmount.

**Comment by natew** [comment]
Final question, if I'm using bluebird in my app, does this add extra weight with it's promises? I think it's more of

**Comment by pluma** [comment]
`axn`, which `fynx` uses, relies on the global `Promise` function to exist and be ES6-compatible (which I think bluebird is), so you probably just need to make sure to set `if (typeof window !== 'undefined') window.Promise = require('bluebird');` (or something like that) somewhere in your code before the first async action is called.

If you're not already using bluebird, that will of course add the extra weight of bluebird itself. But Fynx doesn't provide its own promise implementation or anything silly like that.
